version: '2.3'

networks:
  snare_local:

services:

# Snare service
  snare:
    build: .
    container_name: snare
    restart: always
    stop_signal: SIGKILL
    tty: true
    networks:
     - snare_local
    ports:
     - "8081:8081"
    image: "andy1ww11o2/snare:latest"
    command:  sh -c "clone --target http://www.tenmax.com && snare --no-dorks true --auto-update false --host-ip 0.0.0.0 --port 8081 --page-dir www.tenmax.com --tanner xxx.xxx.xxx.xxx"
